site:
  title: "Laptenok Labs"
  profiles:
    - https://www.linkedin.com/in/marklaptenok/
    - https://github.com/marklaptenok
    - https://t.me/codelearning_online
    - https://laptenoklabspodcasts.mave.digital/
    - https://open.spotify.com/show/4WHR3Gho9yEczk0R0qkQth
    - https://profi.ru/profile/LaptenokMA/
    - https://www.instagram.com/laptenok_labs/
